# Generated by Django 5.2 on 2026-05-14 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('direction', 'Direction'), ('equipe', 'Équipe'), ('projet', 'Projet')], default='equipe', max_length=20, verbose_name='Type')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='groups.group', verbose_name='Groupe parent')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_groups', to='accounts.person', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
            ],
            options={
                'verbose_name': 'Appartenance au groupe',
                'verbose_name_plural': 'Appartenances aux groupes',
                'unique_together': {('person', 'group')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='groups.GroupMembership', to='accounts.person', verbose_name='Membres'),
        ),
    ]
