# Generated by Django 5.2 on 2026-05-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('groups', '0002_alter_groupmembership_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('file', models.FileField(upload_to='group_files/', verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='groups.group', verbose_name='Groupe')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='accounts.person', verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Fichier du groupe',
                'verbose_name_plural': 'Fichiers du groupe',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
