# Generated by Django 5.2 on 2026-05-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('direction', 'Direction'), ('equipe', 'Équipe'), ('projet', 'Projet'), ('communaute', 'Communauté')], default='equipe', max_length=20, verbose_name='Type'),
        ),
    ]
