# Generated by Django 5.2 on 2026-05-14 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('pdf_file', models.CharField(blank=True, max_length=500, verbose_name='Fichier PDF (clé storage)')),
                ('nb_slides', models.PositiveIntegerField(default=5, verbose_name='Nombre de slides souhaité')),
                ('nb_questions', models.PositiveIntegerField(default=5, verbose_name='Nombre de questions souhaité')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to='accounts.person', verbose_name='Créé par')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='groups.group', verbose_name='Groupe')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Ordre')),
                ('text', models.TextField(verbose_name='Question')),
                ('choice_a', models.CharField(max_length=500, verbose_name='Choix A')),
                ('choice_b', models.CharField(max_length=500, verbose_name='Choix B')),
                ('choice_c', models.CharField(max_length=500, verbose_name='Choix C')),
                ('choice_d', models.CharField(max_length=500, verbose_name='Choix D')),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Bonne réponse')),
                ('explanation', models.TextField(blank=True, verbose_name='Explication')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Ordre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='courses.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
                'ordering': ['order'],
            },
        ),
    ]
