# Generated by Django 5.2 on 2026-05-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_pdf_file'),
        ('groups', '0003_groupfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title', 'group')},
        ),
    ]
