# Generated by Django 5.2 on 2026-05-14 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Score (%)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='courses.course', verbose_name='Cours')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='accounts.person', verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Participation',
                'verbose_name_plural': 'Participations',
                'ordering': ['-completed_at'],
                'unique_together': {('person', 'course')},
            },
        ),
    ]
