# Generated by Django 5.2 on 2026-05-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='answers',
            field=models.TextField(blank=True, default='{}', verbose_name='Réponses (JSON)'),
        ),
    ]
