# Generated by Django 5.2 on 2026-05-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0002_participation_answers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
    ]
