# Generated by Django 5.2 on 2026-05-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0003_remove_unique_together_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='attempt',
            field=models.PositiveIntegerField(default=1, verbose_name='Tentative n°'),
        ),
    ]
